site_name: 孫葛數學線上題庫
theme:
  name: material
  features:
    - navigation.tabs
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - 首頁: index.md
  - 解題影片庫:
    - '【112學年度】【武陵高中】【高一上第二次數學段考】【直線與圓】【填充8】': '_112學年度__武陵高中__高一上第二次數學段考__直線與圓__填充8_.md'
    - '【111學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】【計算證明12】': '_111學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析__計算證明12_.md'
    - '【112學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】【填充6】': '_112學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析__填充6_.md'
    - '【113學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】【單選1】': '_113學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析__單選1_.md'
    - '【113學年度】【武陵高中】【高一上第三次數學段考】【直線與圓】【填充3】': '_113學年度__武陵高中__高一上第三次數學段考__直線與圓__填充3_.md'
    - '【112學年度】【武陵高中】【高一上第一次數學段考】【數與式】【填充(Ⅱ)7】': '_112學年度__武陵高中__高一上第一次數學段考__數與式__填充(Ⅱ)7_.md'
    - '【113學年度】【武陵高中】【高一上第一次數學段考】【數與式】【填充9】': '_113學年度__武陵高中__高一上第一次數學段考__數與式__填充9_.md'
    - '【113學年度】【武陵高中】【高一上第一次數學段考】【數與式】【填充5】': '_113學年度__武陵高中__高一上第一次數學段考__數與式__填充5_.md'
    - '【112學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】【填充5】': '_112學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析__填充5_.md'
    - '【111學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】': '_111學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析_.md'
    - '【112學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】': '_112學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析_.md'
    - '【112學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】【填充4】': '_112學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析__填充4_.md'
    - '【113學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】【選填F】': '_113學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析__選填F_.md'
    - '【112學年度】【武陵高中】【高一上第三次數學段考】【多項式】【填充3】': '_112學年度__武陵高中__高一上第三次數學段考__多項式__填充3_.md'
    - '【112學年度】【武陵高中】【高一上第二次數學段考】【直線與圓】【計算1】': '_112學年度__武陵高中__高一上第二次數學段考__直線與圓__計算1_.md'
    - '【113學年度】【武陵高中】【高一下第二次數學段考】【排列組合&amp;機率期望值】【填充E】': '_113學年度__武陵高中__高一下第二次數學段考__排列組合&amp;機率期望值__填充E_.md'
    - '【113學年度】【武陵高中】【高一下第二次數學段考】【排列組合&amp;機率期望值】【填充A】': '_113學年度__武陵高中__高一下第二次數學段考__排列組合&amp;機率期望值__填充A_.md'
    - '【113學年度】【武陵高中】【高一上第三次數學段考】【直線與圓】【多選1】': '_113學年度__武陵高中__高一上第三次數學段考__直線與圓__多選1_.md'
    - '【113學年度】【武陵高中】【高一上第三次數學段考】【直線與圓】【填充11】': '_113學年度__武陵高中__高一上第三次數學段考__直線與圓__填充11_.md'
    - '【113學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】【證明題】': '_113學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析__證明題_.md'
    - '【112學年度】【武陵高中】【高一上第一次數學段考】【數與式】【計算證明1】': '_112學年度__武陵高中__高一上第一次數學段考__數與式__計算證明1_.md'
    - '【111學年度】【武陵高中】【高一上第三次數學段考】【多項式】【填充8】': '_111學年度__武陵高中__高一上第三次數學段考__多項式__填充8_.md'
    - '【113學年度】【武陵高中】【高一上第二次數學段考】【多項式】【選填F】': '_113學年度__武陵高中__高一上第二次數學段考__多項式__選填F_.md'
    - '【113學年度】【武陵高中】【高一下第二次數學段考】【排列組合&amp;機率期望值】【題組3】': '_113學年度__武陵高中__高一下第二次數學段考__排列組合&amp;機率期望值__題組3_.md'
    - '【113學年度】【武陵高中】【高一下第二次數學段考】【排列組合&amp;機率期望值】【填充C】': '_113學年度__武陵高中__高一下第二次數學段考__排列組合&amp;機率期望值__填充C_.md'
    - '【113學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】【選填E】': '_113學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析__選填E_.md'
    - '【111學年度】【武陵高中】【高一下第三次數學段考】【期望值&amp;三角比】【填充5】': '_111學年度__武陵高中__高一下第三次數學段考__期望值&amp;三角比__填充5_.md'
    - '【112學年度】【武陵高中】【高一上第一次數學段考】【數與式】【填充(Ⅰ)1】': '_112學年度__武陵高中__高一上第一次數學段考__數與式__填充(Ⅰ)1_.md'
    - '【113學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】【選填B】': '_113學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析__選填B_.md'
    - '【112學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】【填充8】': '_112學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析__填充8_.md'
    - '【111學年度】【武陵高中】【高一上第二次段考】【數學科】【直線與圓】【多選3】': '_111學年度__武陵高中__高一上第二次段考__數學科__直線與圓__多選3_.md'
    - '【112學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】【填充3】': '_112學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析__填充3_.md'
    - '【113學年度】【武陵高中】【高一上第一次數學段考】【數與式】【填充6】': '_113學年度__武陵高中__高一上第一次數學段考__數與式__填充6_.md'
    - '【112學年度】【武陵高中】【高一上第一次數學段考】【數與式】【多選2】': '_112學年度__武陵高中__高一上第一次數學段考__數與式__多選2_.md'
    - '【112學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】【多選1】': '_112學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析__多選1_.md'
    - '【112學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】【填充9】': '_112學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析__填充9_.md'
    - '【113學年度】【武陵高中】【高一上第二次數學段考】【多項式】【選填D】': '_113學年度__武陵高中__高一上第二次數學段考__多項式__選填D_.md'
    - '【111學年度】【武陵高中】【高一上第三次數學段考】【多項式】【填充7】': '_111學年度__武陵高中__高一上第三次數學段考__多項式__填充7_.md'
    - '【111學年度】【武陵高中】【高一下第三次數學段考】【期望值&amp;三角比】【填充1】': '_111學年度__武陵高中__高一下第三次數學段考__期望值&amp;三角比__填充1_.md'
    - '【113學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】': '_113學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析_.md'
    - '【113學年度】【武陵高中】【高一上第一次數學段考】【數與式】【填充14】': '_113學年度__武陵高中__高一上第一次數學段考__數與式__填充14_.md'
    - '【111學年度】【武陵高中】【高一上第二次段考】【數學科】【直線與圓】【填充6】': '_111學年度__武陵高中__高一上第二次段考__數學科__直線與圓__填充6_.md'
    - '【111學年度】【武陵高中】【高一下第三次數學段考】【期望值&amp;三角比】【單選2】': '_111學年度__武陵高中__高一下第三次數學段考__期望值&amp;三角比__單選2_.md'
    - '【112學年度】【武陵高中】【高一下第三次數學段考】【期望值&amp;三角比】【填充4】': '_112學年度__武陵高中__高一下第三次數學段考__期望值&amp;三角比__填充4_.md'
    - '【113學年度】【武陵高中】【高一下第二次數學段考】【排列組合&amp;機率期望值】【填充D】': '_113學年度__武陵高中__高一下第二次數學段考__排列組合&amp;機率期望值__填充D_.md'
    - '【112學年度】【武陵高中】【高一上第一次數學段考】【數與式】【填充(Ⅱ)5】': '_112學年度__武陵高中__高一上第一次數學段考__數與式__填充(Ⅱ)5_.md'
    - '【113學年度】【武陵高中】【高一上第二次數學段考】【多項式】【單選1】': '_113學年度__武陵高中__高一上第二次數學段考__多項式__單選1_.md'
    - '【113學年度】【武陵高中】【高一下第二次數學段考】【排列組合&amp;機率期望值】【多選1】': '_113學年度__武陵高中__高一下第二次數學段考__排列組合&amp;機率期望值__多選1_.md'
    - '【112學年度】【武陵高中】【高一上第三次數學段考】【多項式】【多選2】': '_112學年度__武陵高中__高一上第三次數學段考__多項式__多選2_.md'
    - '【111學年度】【武陵高中】【高一下第三次數學段考】【期望值&amp;三角比】【填充6】': '_111學年度__武陵高中__高一下第三次數學段考__期望值&amp;三角比__填充6_.md'
    - '【111學年度】【武陵高中】【高一下第二次數學段考】【排列組合&amp;機率】【填充3】': '_111學年度__武陵高中__高一下第二次數學段考__排列組合&amp;機率__填充3_.md'
    - '【112學年度】【武陵高中】【高一上第一次數學段考】【數與式】【計算證明2】': '_112學年度__武陵高中__高一上第一次數學段考__數與式__計算證明2_.md'
    - '【111學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】【多選2】': '_111學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析__多選2_.md'
    - '【111學年度】【武陵高中】【高一下第三次數學段考】【期望值&amp;三角比】【多選3】': '_111學年度__武陵高中__高一下第三次數學段考__期望值&amp;三角比__多選3_.md'
    - '【111學年度】【武陵高中】【高一下第三次數學段考】【期望值&amp;三角比】【多選2】': '_111學年度__武陵高中__高一下第三次數學段考__期望值&amp;三角比__多選2_.md'
    - '【112學年度】【武陵高中】【高一上第一次數學段考】【數與式】【多選1】': '_112學年度__武陵高中__高一上第一次數學段考__數與式__多選1_.md'
    - '【112學年度】【武陵高中】【高一上第一次數學段考】【數與式】【填充(Ⅱ)6】': '_112學年度__武陵高中__高一上第一次數學段考__數與式__填充(Ⅱ)6_.md'
    - '【112學年度】【武陵高中】【高一上第三次數學段考】【多項式】【多選3】': '_112學年度__武陵高中__高一上第三次數學段考__多項式__多選3_.md'
    - '【111學年度】【武陵高中】【高一下第三次數學段考】【期望值&amp;三角比】【填充4】': '_111學年度__武陵高中__高一下第三次數學段考__期望值&amp;三角比__填充4_.md'
    - '【112學年度】【武陵高中】【高一下第三次數學段考】【期望值&amp;三角比】【填充2】': '_112學年度__武陵高中__高一下第三次數學段考__期望值&amp;三角比__填充2_.md'
    - '【111學年度】【武陵高中】【高一下第三次數學段考】【期望值&amp;三角比】【填充9】': '_111學年度__武陵高中__高一下第三次數學段考__期望值&amp;三角比__填充9_.md'
    - '【113學年度】【武陵高中】【高一下第二次數學段考】【排列組合&amp;機率期望值】【題組2】': '_113學年度__武陵高中__高一下第二次數學段考__排列組合&amp;機率期望值__題組2_.md'
    - '【113學年度】【武陵高中】【高一上第一次數學段考】【數與式】【填充10】': '_113學年度__武陵高中__高一上第一次數學段考__數與式__填充10_.md'
    - '【113學年度】【武陵高中】【高一下第二次數學段考】【排列組合&amp;機率期望值】【題組1】': '_113學年度__武陵高中__高一下第二次數學段考__排列組合&amp;機率期望值__題組1_.md'
    - '【113學年度】【武陵高中】【高一下第二次數學段考】【排列組合&amp;機率期望值】【填充B】': '_113學年度__武陵高中__高一下第二次數學段考__排列組合&amp;機率期望值__填充B_.md'
    - '【113學年度】【武陵高中】【高一下第二次數學段考】【排列組合&amp;機率期望值】【題組4】': '_113學年度__武陵高中__高一下第二次數學段考__排列組合&amp;機率期望值__題組4_.md'
    - '【113學年度】【武陵高中】【高一上第三次數學段考】【直線與圓】': '_113學年度__武陵高中__高一上第三次數學段考__直線與圓_.md'
    - '【112學年度】【武陵高中】【高一下第三次數學段考】【期望值&amp;三角比】【多選2】': '_112學年度__武陵高中__高一下第三次數學段考__期望值&amp;三角比__多選2_.md'
    - '【112學年度】【武陵高中】【高一上第一次數學段考】【數與式】【填充(Ⅱ)2】': '_112學年度__武陵高中__高一上第一次數學段考__數與式__填充(Ⅱ)2_.md'
    - '【113學年度】【武陵高中】【高一上第一次數學段考】【數與式】【多選1】': '_113學年度__武陵高中__高一上第一次數學段考__數與式__多選1_.md'
    - '【112學年度】【武陵高中】【高一上第三次數學段考】【多項式】': '_112學年度__武陵高中__高一上第三次數學段考__多項式_.md'
    - '【113學年度】【武陵高中】【高一上第一次數學段考】【數與式】【填充3】': '_113學年度__武陵高中__高一上第一次數學段考__數與式__填充3_.md'
    - '【113學年度】【武陵高中】【高一上第一次數學段考】【數與式】【多選2】': '_113學年度__武陵高中__高一上第一次數學段考__數與式__多選2_.md'
    - '【111學年度】【武陵高中】【高一下第三次數學段考】【期望值&amp;三角比】': '_111學年度__武陵高中__高一下第三次數學段考__期望值&amp;三角比_.md'
    - '【111學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】【填充10】': '_111學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析__填充10_.md'
    - '【113學年度】【武陵高中】【高一上第一次數學段考】【數與式】【填充4】': '_113學年度__武陵高中__高一上第一次數學段考__數與式__填充4_.md'
    - '【111學年度】【武陵高中】【高一下第一次數學段考】【數列級數&amp;數據分析】【多選1】': '_111學年度__武陵高中__高一下第一次數學段考__數列級數&amp;數據分析__多選1_.md'
    - '【113學年度】【武陵高中】【高一上第一次數學段考】【數與式】【填充12】': '_113學年度__武陵高中__高一上第一次數學段考__數與式__填充12_.md'
    - '【112學年度】【武陵高中】【高一下第三次數學段考】【期望值&amp;三角比】【填充9】': '_112學年度__武陵高中__高一下第三次數學段考__期望值&amp;三角比__填充9_.md'
    - '【111學年度】【武陵高中】【高一下第二次數學段考】【排列組合&amp;機率】【填充7】': '_111學年度__武陵高中__高一下第二次數學段考__排列組合&amp;機率__填充7_.md'
    - '【112學年度】【武陵高中】【高一下第三次數學段考】【期望值&amp;三角比】【混合題】': '_112學年度__武陵高中__高一下第三次數學段考__期望值&amp;三角比__混合題_.md'
    - '【112學年度】【武陵高中】【高一下第三次數學段考】【期望值&amp;三角比】【多選4】': '_112學年度__武陵高中__高一下第三次數學段考__期望值&amp;三角比__多選4_.md'
    - '【111學年度】【武陵高中】【高一下第二次數學段考】【排列組合&amp;機率】【填充14】': '_111學年度__武陵高中__高一下第二次數學段考__排列組合&amp;機率__填充14_.md'
